apiVersion: v1
kind: ConfigMap
metadata:
  name: wandb-preprocess
data:
  S3_BUCKET: s3://wandb-finbert/
  MOUNT_PATH: /shared-efs

---
apiVersion: v1
kind: Pod
metadata:
  name: wandb-preprocess-pod
spec:
  containers:
  - name: wandb-preprocess-pod-test
    image: 999701187340.dkr.ecr.us-west-2.amazonaws.com/wandb
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    #envFrom:
    #- configMapRef:
    #    name: one-file-map
    #command: ["/bin/bash"]
    #args: ["-c", "/run-one-file.sh"]
    volumeMounts:
    - name: efs-pvc
      mountPath: /shared-efs
  volumes:
  - name: efs-pvc
    persistentVolumeClaim:
      claimName: efs-claim
  restartPolicy: Never
